# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20150707_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='roles',
        ),
        migrations.DeleteModel(
            name='GroupRole',
        ),
    ]
