# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20150707_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmemberprofile',
            name='current_charge_regime',
            field=models.CharField(choices=[('tacho', 'Tacho'), ('block2block', 'Block-to-block'), ('hobbs', 'Hobbs'), ('airborne', 'Airborne')], max_length=20),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='default_charge_regime',
            field=models.CharField(choices=[('tacho', 'Tacho'), ('block2block', 'Block-to-block'), ('hobbs', 'Hobbs'), ('airborne', 'Airborne')], default='tacho', max_length=20),
        ),
    ]
