# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20160520_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmemberprofile',
            name='role',
        ),
    ]
