# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_remove_groupmemberprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('contact_info', models.CharField(max_length=100)),
                ('group_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.GroupProfile')),
            ],
        ),
    ]
