# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20160116_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablesreceipt',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='techlogentry',
            name='charge_regime',
            field=models.CharField(choices=[('tacho', 'Tacho'), ('block2block', 'Block-to-block'), ('hobbs', 'Hobbs'), ('airborne', 'Airborne')], max_length=20),
        ),
    ]
