# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroplanes', '0005_auto_20150921_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('50HOURS1', '50 hours (first)'), ('50HOURS2', '50 hours (second)'), ('150HOURS', '150 hours'), ('ANNUAL', 'Annual')], max_length=10),
        ),
    ]
